### ISSUE TITLE
Setup.txt mentions different config than LilyGo

### ISSUE THREAD

**Issue by dapug** [teastainGit/LilyGO-T-display-S3-setup-and-examples#1]
The board is 16MB Flash, no?  The config png (Arduino_Config.png) shows Flash Size: 16MB, but this setup.txt says to set it to 8MB.  Why?

The config from LilyGo also shows partition as "Huge App", but Setup.txt says to set it to "8M with spiffs".  Why?

Also note, if you run code that requires PSRAM, you will have issues unless you configure to use PSRAM, which apparently is disabled by default on the board "ESP32S3 Dev Module" (aka "esp32-s3-devkitc-1").

I'm unclear what the setup instructions is trying to help people do, when missing config this board actually has.  If it is just a demo of hothead, that's cool, but its not really titled or pitched that way.

**Comment by teastainGit** [comment]
Why?
Dozens or more people have been helped by this Repo.
Thank you for pointing out that LilyGO changed the setup parameters and I forgot to update the setup text.
(the old parameters worked fine, but they announced new settings…so I posted a screenshot…)
Done.



Cheers !
Terry Stainton

***@***.***
