### ISSUE TITLE
need nrf24l01 gpio possibles

### ISSUE THREAD

**Issue by pioioTwo** [teastainGit/LilyGO-T-display-S3-setup-and-examples#10]
Need pinout possibles for nrf24l01 and for usage rf24 examples.

**Comment by teastainGit** [comment]
Hi, thanks for reaching out.
This GitHub repository is primarily to support the 'LilyGO T-Display S3' dev board.
Almost all of the pins are multi-purpose and you should have no problem connecting some or other nrf24l01  board and use some other  ESP32 app or sketch to run it.
-Terry
