### ISSUE TITLE
Closed: My s3 has a black screen  the lights on the inside turn on but nothing on the screen

### ISSUE THREAD

**Issue by Ho0dLuMsAPimP** [teastainGit/LilyGO-T-display-S3-setup-and-examples#11]

**Comment by svdrummer** [comment]
Have a look at all the past/closed issues. Explanation and fix is there

**Comment by teastainGit** [comment]
Read through the T-DisplayS3_Setup.txt and you will see:
If you do an Arduino libraries update you WILL have to edit the "User_Setup_Select.h" to comment-out the line:
"//#include <User_Setup.h> // Default setup is root library folder"
AND un-comment:
"#include <User_Setups/Setup206_LilyGo_T_Display_S3.h> // For the LilyGo T-Display S3 based ESP32S3 with ST7789 170 x 320 TFT"
which is about halfway down the huge file of setups.
OR
(You will find an edited copy of "User_Setup_Select.h" here in may repository)

F) Even after uploading the HotHead sketch you get no image on the LCD, just black or white background, 
	but you can see the Tick/Tock in Serial Monitor:
	You may not have copied ALL the files from the LilyGO repository folder 'lib' and fully replaced the
	ones in your Libraries folder or you did NOT resist the temptation to do an Arduino Library Update!
	The current Arduino Library for TFT_eSPI is now Bodmer's official v2.5 but there are still 
	setups to do.
