### ISSUE TITLE
new library

### ISSUE THREAD

**Issue by svdrummer** [teastainGit/LilyGO-T-display-S3-setup-and-examples#2]
Has anyone got the new library to work?
In user_setup_select, I uncommented the line below.
#include <User_Setups/Setup206_LilyGo_T_Display_S3.h>

In my case, the text is all over the screen.

I do have the code printed sideways in my code, ie Rotation = 3
I also downloaded the zip from the github as the setup files are different on the Arduino library manager

**Comment by teastainGit** [comment]
OMG, sorry to have missed your Issue!
Did you ever get the "Arduino Updates Library" to work?
It's great that all you guys,  tyeth, ElectricDream5, etc  brought LilyGO to task...
but the Average Arduino-er will go onto another project, absentmindedly "Update All Libraries" and Blam, the LilyGO T-Display S3 stops working.
I will "have a go" today and see.
Thanks, Terry
