### ISSUE TITLE
VSPI not defined ...

### ISSUE THREAD

**Issue by icedawn** [teastainGit/LilyGO-T-display-S3-setup-and-examples#3]
Any idea what this is?  It's in the LilyGO TFT library code, but you may have a work around?

In file included from /Users/ecrump/scratch/arduino/esp32/lilygo/teastainGit/LilyGO-T-display-S3-setup-and-examples-main/HotHead/HotHead.ino:2:
/Users/ecrump/Documents/Arduino/libraries/TFT_eSPI/TFT_eSPI.h:302:21: error: 'VSPI' was not declared in this scope
     uint8_t  port = VSPI;
                     ^~~~
/Users/ecrump/Documents/Arduino/libraries/TFT_eSPI/TFT_eSPI.h:302:21: note: suggested alternative: 'SPI'
     uint8_t  port = VSPI;
                     ^~~~
                     SPI

exit status 1

Compilation error: exit status 1

**Comment by teastainGit** [comment]
Hi! Couple of Q's:
I have never run across this error, sorry!
Are you using the Arduino V2.0.3?
Can you tell me where you got the TFT_eSPI  Library folder and it's drivers?
Is it from Arduino? (The one installed by Arduino)
Is it from LiliGO's repository when you downloaded and unzipped the files?
Have you done the Arduino Library Updates on this Library ?

These pointed questions will help me understand your situation!!!

Thanks, Terry

**Comment by teastainGit** [comment]
OK, first off I see a problem, that could improve your evening.
https://github.com/Xinyuan-LilyGO/TTGO-T-Display is NOT the correct source for the LilyGO T-Display S3 .
TTGO is an older board that I always wanted until the new T-Display S3 came out late this summer.
It is in fact:
https://github.com/Xinyuan-LilyGO/T-Display-S3
Subtle difference. The TTGO is in fact a SPI display but the LilyGO T-Display S3 is a larger  8 bit parallel LCD, not SPI as the naming implies. LilyGO T-Display S3 users have been fighting with LilyGO over this and just this week the author of TFT_eSPI agreed and issued a modified version, which I was able to beta-test and it works fine.
That is why -currently- you need to delete the TFT_eSPI Library and replace it with LilyGO T-Display S3 version and resist the temptation to update it  through Arduino.
My repository is a response to my grief and sweat so I can help others.  
So, please confirm which of the two boards we are talking about!
Terry

**Comment by icedawn** [comment]
OH!!!!  LOL, that is excellent!  Thank you for catching that Terry ... that's the piece I was in no danger of seeing ;-).  I've got the T-Display-S3 boards.  

I'll give this a try later tonight and confirm!

**Comment by icedawn** [comment]
Confirmed!  That did the trick!  I was using the TTGO sources for the TFT_eSPI, not the T-Display-S3 version.  Your demo compiled and popped up without any fuss on the T-Display-S3 device ;-)

I owe you a few beers!

**Comment by teastainGit** [comment]
My pleasure!
