### ISSUE TITLE
Memory partition

### ISSUE THREAD

**Issue by laverdanny** [teastainGit/LilyGO-T-display-S3-setup-and-examples#4]
Hi [teastainGit]

you suggest 
Flash Size: "16MB (128Mb)"
Partition Scheme: "Huge APP (3MB No OTA/1MB SPIFFS)"
It means to me only 4 MB are used, is there no way to get the full 16 MB ?
(Maybe a silly question, sorry for that in such a case)

**Comment by teastainGit** [comment]
I am not an expert in memory use! This is the recommendation from LilyGO .
It may mean that most memory is partitioned for binary file of the program and the rest is data?
Other schemes also work. They used to call for 8Mb with Spiffs, but they changed it.
You might pose this question back on the LilyGO repository Issues to get LilyGO to answer this!
