### ISSUE TITLE
Dimming not accurate (esp. 100%)

### ISSUE THREAD

**Issue by pitlochry** [teastainGit/LilyGO-T-display-S3-setup-and-examples#6]
Thank you for your code.
I have this T-Display-S3 and experimented with your code. Making it dim and bright, I observed:

1. The dimming is not nearly linear
2. Making it bright to 255 (100%) can result in two things: 255 is either much brighter than 250 (huge gap in brightness) or 255 is even less bright than 250 - although 255 should be brightest. Seems to be random.

The non-linear dimming (1.) can be resolved in software, but for the 2. problem I have found no solution. I experimented with other frequencies and other resolutions but to no avail: From the second highest number to the highest number there is often a huge gap in brightness and sometimes the highest number does not result into the highest brightness. 

Does someone know the reason for this, and how to solve it? Thank you.

**Comment by svdrummer** [comment]
I just threw this together incase it may help.
Output is a scale of 0 to 100%

The PWM output from the esp32 is just that, a PWM output. The LED current is not linear for this range

you could try the map function.
uint8_t dimmer_level_input;   // a number between 0 to 100
uint8_t dimmer_level_output; // value to insert in your PWM function to dim the LED


dimmer_level_output  = map(dimmer_level_input,0,100,245,255);

**Comment by teastainGit** [comment]
My sketch is buggy. It provides dimming by traditional means, PWM and ledc, but I too have noticed the glitches.
The backlight chip requires pulses like key presses and only provides for 15 levels, according to the AW9364DNR backlight dimming chip  mfg.
I will add notices that Dimming is now under development and make it my next priority.
I got distracted by my new LilyGO T-HMI which is a fantastic improvement in engineering design and answers all of my complaints against the LilyGO T-Display S3 !!!
Thank you for your patience.
-Terry

**Comment by teastainGit** [comment]
[pitlochry](https://github.com/pitlochry)! Sorry about the confusion. The backlight is NOT controlled by PWM.
It is controlled by input pulses from brightest to dimmest and then jumps back to brightest.
The code is actually simpler but you cannot increase brightness without "going around".
The signal timing is very fussy.
I have updated the repository!
-Terry

**Comment by pitlochry** [comment]
Thankyou. With the method of the aw9364, there is no stepless dimming possible? Only to make sure. The screen is dimmed by stepping internal resistors or how is it done internally?

**Comment by teastainGit** [comment]
The aw9364 is a chip on the board that controls current to the backlight.
It has 15 steps, dimmed by single PB pushes or holding the PB to go quicker and then it "comes around" to full. You cannot go the other way!  (Or know what level you are at now)
The aw9364 datasheet is included in the repository but here are highlights.
<img width="775" alt="Screenshot 2023-04-18 at 12 00 17 PM" src="https://user-images.githubusercontent.com/80008504/232836004-0081cd58-e193-4e93-82fe-b3ce6f071314.png">
<img width="1188" alt="Screenshot 2023-04-18 at 12 00 53 PM" src="https://user-images.githubusercontent.com/80008504/232836114-ec2f5f99-5e46-4f0f-8c7f-8b037bb94195.png">
<img width="1188" alt="Screenshot 2023-04-18 at 12 00 53 PM" src="https://user-images.githubusercontent.com/80008504/232836135-4f2b0875-96e3-44c9-a80b-7def47f9fac6.png">

I think the PB/step method saves execution time by only being called by the PB, it is idle during the rest of your application's running. (Except of course the C code to read the input.)
The PWM method has to run continuously.
Hope this helps!
-Terry
