### ISSUE TITLE
T-Display-S3-main

### ISSUE THREAD

**Issue by AlanLL** [teastainGit/LilyGO-T-display-S3-setup-and-examples#7]
I have followed your your set up instructions, and when I compile the program there is a message:- "loading library from c:\Users\Alan_\Documents\Arduino\libraries\T-Display-S3-main: invalid library: no header files found"
Is it because there is a missing file "library.properties" ??

**Comment by teastainGit** [comment]
Hello Alan. I am just stepping out.
I will get back to you in a couple of hours.
Cheer -Terry

**Comment by teastainGit** [comment]
Alan, I saw your Issue over on LilyGO LilyGO T-Display S3 GitHub !
Could you re-cap for me what it is NOW doing, having tried all the previous advice?
I'm sure we can get to the bottom of this!
-Terry

**Comment by AlanLL** [comment]
I am using Arduino 2.1.1 IDE.
The T-Display came with an Instruction page, which I followed
 Step 1 https://github.com/Xinyuan-LilyGO/T-Display-S3#quick-start
Step 2 https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/firmware
I uploaded both firmwares and they tested OK
Step 3 Where just notes on the firmware.
Step 4 https://youyu.be/8uFAKa5blyg
On watching this video again I noticed tha he held down the BOOT key before pluging the USB cable in. This turned the screen black and I was able to upload the tft.ini . I then realised this has to be done every time
I wanted to upload a new program.
But any time a program is uploaded or compiled you get this message: "loading library from c:\Users\Alan_\Documents\Arduino\libraries\T-Display-S3-main: invalid library: no header files found"
but the program works, which was my original post initial post.
The coding upload is now sorted, BUT nowhere does it say that the BOOT button must be held down while the USB lead is inserted.
Thanks for your help it made me look at the Video again where they held the BOOT key down when pluging in the USB.
I think this point should be included in the instructions.

**Comment by teastainGit** [comment]
Thank YOU for your feedback, I have added the hold-boot-plug-in technique...
(to my 
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples 
setup text. But I do not have access to LilyGO!)
Usually I can edit sketches and re-upload on my LilyGO T-Display S3 that is plugged in, without having to click on the Board and Connection menu. 
If the sketch has a fault and is crashing or if the Loop scan time is too short, I have to do the "hold Boot while resetting then release Boot" trick.
I may have only once done the unplug, hold boot while re-plugging.
The worst thing you can do is upload the Arduino IDE blank sketch with no timer delay !!!
You cannot get the thing's attention after that, it is stuck in a microsecond scan time.
If you read every line in my setup text you will have a good understanding of what can go wrong and how to get out of it.
-Terry

**Comment by AlanLL** [comment]
Prviously to reset the upload method was not working because I was holding down the BOOT key and pressing I014 button (I thought this was the RST key) Now I Know the RST button is on the side of the BOOT button.
It looks like I've caused my self all of these problems because I did'nt RTFM!

**Comment by gekopmac** [comment]
Dear Terry Stainton,

This was what I had been looking forward to for weeks, with your documtation it was a piece of cake. Here everything works even the touch display, the doc from Lilygo is/was not complete to get everything working, thank you very much from Holland.
With kind regards,

**Comment by teastainGit** [comment]
Thanks for letting me know it helped!
When I got mine last year I had a very difficult time and almost gave up, it’s that bad!
So I complied all my notes and test programs into my GitHub repository.
Cheers from Canada!



Cheers !
Terry Stainton

***@***.***
