### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CodingSpiderFox** [teastainGit/LilyGO-T-display-S3-setup-and-examples#8]
Hello,

Thank you very much for providing these resources :)

Could you please add a license to the repository?

Thank you in advance :)

**Comment by teastainGit** [comment]
Interesting, what is that for?
-Terry

**Comment by CodingSpiderFox** [comment]
I am not a lawyer but to my understanding - at least in the German speaking jurisdictions (Germany, Austria, Switzerland) you cannot contribute to or maybe not even use the resources without permission.

A suitable license (either copyleft or some other) should solve this problem.

**Comment by CodingSpiderFox** [comment]
Thx :)
