### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by marcusobrien** [teastainGit/LilyGO-T-display-S3-setup-and-examples#9]
Hi, 

I'm trying to follow the setup instructions - but I'm getting confused about the folder names, and whether they are for the Arudino IDE, my Arduino Sketch folder, this repo, or the T-Display S3 repo. If the following is correct, please let me know and I can push request it if needed.

**T-DisplayS3_Setup.txt**
The first instructions are clear 

To begin...you need to download the Zip file from LilyGO's own GitHub:
https://github.com/Xinyuan-LilyGO/T-Display-S3
by pressing the green button "Code" and after downloading, expand the Zip.

So I am doing this
1. Download the Zip file from LilyGO's own GitHub: https://github.com/Xinyuan-LilyGO/T-Display-S3 by pressing the green button "Code" and after downloading, expand the Zip.
2. In the T-Display-S3-main/lib folder (unzipped from above instruction), delete folders “TFT_eSPI" and ‘lvgl" and delete the file “lv_conf.h”

Now the instructions say to download **another** zip file - is this a different zip to 1 above or the same ?

"Download the latest LilyGO T-Display S3 zip from GitHub. (It will not install by using the old Sketch pulldown called "Include Library> Add .ZIP Library, as the ZIP file is not a Library ZIP, but a Product Download that contains other things such as Examples, libraries and documentation. ) Expand LilyGO’s zip file and…

4. This unzipped file will not install into the Arduino IDE by using the old Sketch pulldown from "Include Library> Add .ZIP Library", because the ZIP file is not a Arduino IDE Library ZIP but a Product Download. It contains other things such as Examples, libraries and documentation. Expand LilyGO’s zip file and…Drag the folder called "T-Display-S3-main” into your Arduino folder. Inside the folder T-Display-S3-main there is a folder called “lib”. Copy the CONTENTS of the folder “lib” (not the actual folder “lib”)  into your  libraries folder and then check that “lib” is empty and delete it.

So for the above, I presume I have to create an Arduino ino sketch folder, and then copy the unzipped t_Display-S3-main into the Arduino ino sketch folder ?

5. Run Arduino IDE, and make a blank sketch and save it (tdisplay.ino) or use an example arduino sketch ino from this repo

6. Copy the folder "T-Display-S3-main” into the same folder as the Arduino ino **Sketch** file. - **Or does this mean the Arduino IDE install folder ?**

7. Inside the folder T-Display-S3-main there is a folder called “lib”. MOVE the CONTENTS of this “lib” folder (not the actual folder “lib”)  into your Arduino Sketch libraries folder, then check that “lib” is empty and delete it. You can find the sketch folder using the ArduinoIDE->"File->Preferences->Sketchbook location".
Your Arduino Sketch libraries folder should now also contain folders called:
lvgl
T-Display-S3-main
TFT_eSPI
and a file called
lv_conf.h
...and recently, many other helpful dependancies.

Have I got the above correct so far?  Thanks in advance for any help.

**Comment by teastainGit** [comment]
OK, I edited the ReadMe and setup and examples for clarity. I will check back here later today!

**Comment by marcusobrien** [comment]
Thanks @teastainGit
